#!/usr/bin/env bash
# Installs nginx on a server and makes it listen on port 80:
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
