#!/usr/bin/env bash
## Function to clean up and exit gracefully
cleanup() {
    echo "Deleting PID file and terminating."
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
